name: Tests
on: push
jobs:
  test:
    name: Node 14
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: make node_modules
    - name: Run tests
      run: make ci-test
    - name: Run linter
      run: make ci-lint
